using System;using System.Data;using System.Drawing;using System.IO;using System.Windows.Forms;
namespace AshkanHotelManager
{
 public partial class AdminCenterForm:Form
 {
  TabControl tabs; DataGridView staffGrid,servicesGrid,auditGrid;
  public AdminCenterForm(){InitializeComponent();Text=App.T("adminCenter");BackColor=Ui.Bg;Build();App.ApplyDirection(this);}
  void Build(){Controls.Clear();var head=new Panel{Dock=DockStyle.Top,Height=92,BackColor=Ui.Navy,Padding=new Padding(24)};head.Controls.Add(new Label{Text=App.T("adminCenter"),Dock=DockStyle.Top,Height=38,ForeColor=Color.White,Font=Ui.Font(22,FontStyle.Bold),TextAlign=App.Persian?ContentAlignment.MiddleRight:ContentAlignment.MiddleLeft});head.Controls.Add(new Label{Text=App.Persian?"کارکنان، خدمات، امنیت داده و تاریخچه فعالیت سامانه":"Staff, services, data safety and system activity",Dock=DockStyle.Bottom,Height=28,ForeColor=Color.FromArgb(203,213,225),Font=Ui.Font(9.5f),TextAlign=App.Persian?ContentAlignment.MiddleRight:ContentAlignment.MiddleLeft});Controls.Add(head);tabs=new TabControl{Dock=DockStyle.Fill,Font=Ui.Font(10,FontStyle.Bold),Padding=new Point(18,8)};tabs.TabPages.Add(Page(App.T("staff"),"Staff",out staffGrid));tabs.TabPages.Add(Page(App.T("services"),"Services",out servicesGrid));tabs.TabPages.Add(AuditPage());tabs.TabPages.Add(ToolsPage());Controls.Add(tabs);tabs.BringToFront();}
  TabPage Page(string title,string table,out DataGridView grid){var pg=new TabPage(title){BackColor=Ui.Bg,Padding=new Padding(16)};var bar=Ui.SurfacePanel();bar.Dock=DockStyle.Top;bar.Height=72;var add=Ui.Btn(App.T("add"));add.Width=130;add.Location=new Point(18,14);add.Click+=(s,e)=>{using(var f=new CrudForm(table,title))f.ShowDialog(this);DataStore.Log("Edit",table,"Records updated");RefreshAll();};var manage=Ui.Ghost(App.Persian?"مدیریت اطلاعات":"Manage records");manage.Width=160;manage.Location=new Point(160,14);manage.Click+=(s,e)=>{using(var f=new CrudForm(table,title))f.ShowDialog(this);DataStore.Log("Edit",table,"Records updated");RefreshAll();};bar.Controls.Add(add);bar.Controls.Add(manage);grid=new DataGridView{Dock=DockStyle.Fill};Ui.Grid(grid);grid.DataSource=new DataView(DataStore.Db.Tables[table]);pg.Controls.Add(grid);pg.Controls.Add(bar);grid.BringToFront();bar.BringToFront();return pg;}
  TabPage AuditPage(){var pg=new TabPage(App.T("audit")){BackColor=Ui.Bg,Padding=new Padding(16)};auditGrid=new DataGridView{Dock=DockStyle.Fill};Ui.Grid(auditGrid);auditGrid.DataSource=new DataView(DataStore.Db.Tables["AuditLog"]);pg.Controls.Add(auditGrid);return pg;}
  TabPage ToolsPage(){var pg=new TabPage(App.T("systemTools")){BackColor=Ui.Bg,Padding=new Padding(22)};var card=Ui.SurfacePanel();card.Dock=DockStyle.Top;card.Height=210;var title=new Label{Text=App.Persian?"امنیت و نگهداری اطلاعات":"Data safety & maintenance",Dock=DockStyle.Top,Height=42,Font=Ui.Font(15,FontStyle.Bold),ForeColor=Ui.Text,TextAlign=App.Persian?ContentAlignment.MiddleRight:ContentAlignment.MiddleLeft};var hint=new Label{Text=App.Persian?"از فایل داده هتل نسخه پشتیبان تهیه کنید یا نسخه قبلی را بازیابی کنید.":"Create a backup of hotel data or restore a previous copy.",Dock=DockStyle.Top,Height=38,Font=Ui.Font(9.5f),ForeColor=Ui.Muted,TextAlign=App.Persian?ContentAlignment.MiddleRight:ContentAlignment.MiddleLeft};var b=Ui.Btn(App.T("backup"));b.Width=180;b.Location=new Point(24,110);b.Click+=(s,e)=>Backup();var r=Ui.Ghost(App.T("restore"));r.Width=180;r.Location=new Point(220,110);r.Click+=(s,e)=>Restore();card.Controls.Add(b);card.Controls.Add(r);card.Controls.Add(hint);card.Controls.Add(title);pg.Controls.Add(card);return pg;}
  void Backup(){if(!File.Exists(DataStore.DataFile)){MessageBox.Show("No data file.");return;}using(var d=new SaveFileDialog{Filter="Hotel backup (*.xml)|*.xml",FileName="AshkanHotel-Backup-"+DateTime.Now.ToString("yyyyMMdd-HHmm")+".xml"})if(d.ShowDialog(this)==DialogResult.OK){File.Copy(DataStore.DataFile,d.FileName,true);DataStore.Log("Backup","System",d.FileName);MessageBox.Show(App.Persian?"نسخه پشتیبان ایجاد شد.":"Backup created.");RefreshAll();}}
  void Restore(){using(var d=new OpenFileDialog{Filter="Hotel backup (*.xml)|*.xml"})if(d.ShowDialog(this)==DialogResult.OK){if(MessageBox.Show(App.Persian?"اطلاعات فعلی با نسخه انتخابی جایگزین شود؟":"Replace current data with selected backup?",App.T("restore"),MessageBoxButtons.YesNo,MessageBoxIcon.Warning)!=DialogResult.Yes)return;File.Copy(d.FileName,DataStore.DataFile,true);MessageBox.Show(App.Persian?"بازیابی انجام شد. برنامه را یک بار ببندید و دوباره اجرا کنید.":"Restore completed. Restart the application.");}}
  void RefreshAll(){if(staffGrid!=null)staffGrid.DataSource=new DataView(DataStore.Db.Tables["Staff"]);if(servicesGrid!=null)servicesGrid.DataSource=new DataView(DataStore.Db.Tables["Services"]);if(auditGrid!=null)auditGrid.DataSource=new DataView(DataStore.Db.Tables["AuditLog"]);}
 }
}
