using System;using System.Data;using System.Drawing;using System.Linq;using System.Windows.Forms;
namespace AshkanHotelManager{public partial class CrudForm:Form{readonly string table;readonly DataGridView grid=new DataGridView();readonly TextBox search=new TextBox();Label count;
public CrudForm(string t,string title){InitializeComponent();table=t;Text=title;Width=1180;Height=720;MinimumSize=new Size(900,600);StartPosition=FormStartPosition.CenterParent;BackColor=Ui.Bg;Build(title);App.ApplyDirection(this);Bind();}
void Build(string title){var head=new Panel{Dock=DockStyle.Top,Height=92,BackColor=Ui.Surface,Padding=new Padding(26,16,26,12)};var h=new Label{Text=title,Dock=DockStyle.Top,Height=38,Font=Ui.Font(22,FontStyle.Bold),ForeColor=Ui.Text,TextAlign=App.Persian?ContentAlignment.MiddleRight:ContentAlignment.MiddleLeft};count=new Label{Dock=DockStyle.Bottom,Height=25,Font=Ui.Font(9),ForeColor=Ui.Muted,TextAlign=App.Persian?ContentAlignment.MiddleRight:ContentAlignment.MiddleLeft};head.Controls.Add(count);head.Controls.Add(h);Controls.Add(head);
var tools=new Panel{Dock=DockStyle.Top,Height=76,BackColor=Ui.Bg,Padding=new Padding(22,14,22,10)};search.Width=280;search.Height=38;search.Text=App.T("search");search.Font=Ui.Font(10);search.TextChanged+=(s,e)=>Bind();var add=Ui.Btn("＋  "+App.T("add"));add.Width=130;add.Click+=(s,e)=>Edit(null);var edit=Ui.Ghost("✎  "+App.T("edit"));edit.Width=130;edit.Click+=(s,e)=>{if(grid.CurrentRow!=null)Edit(((DataRowView)grid.CurrentRow.DataBoundItem).Row);};var del=Ui.Ghost("×  "+App.T("delete"));del.Width=130;del.ForeColor=Ui.Danger;del.Click+=(s,e)=>Delete();var flow=new FlowLayoutPanel{Dock=DockStyle.Fill,FlowDirection=App.Persian?FlowDirection.RightToLeft:FlowDirection.LeftToRight,WrapContents=false};flow.Controls.AddRange(new Control[]{search,add,edit,del});tools.Controls.Add(flow);Controls.Add(tools);
var shell=new Panel{Dock=DockStyle.Fill,BackColor=Ui.Bg,Padding=new Padding(22,4,22,22)};var card=Ui.SurfacePanel();card.Dock=DockStyle.Fill;grid.Dock=DockStyle.Fill;Ui.Grid(grid);grid.CellDoubleClick+=(s,e)=>{if(e.RowIndex>=0&&grid.CurrentRow!=null)Edit(((DataRowView)grid.CurrentRow.DataBoundItem).Row);};card.Controls.Add(grid);shell.Controls.Add(card);Controls.Add(shell);shell.BringToFront();tools.BringToFront();head.BringToFront();}
void Bind(){var dv=new DataView(DataStore.Db.Tables[table]);var q=search.Text.Trim();if(q!=""&&q!=App.T("search")){var parts=DataStore.Db.Tables[table].Columns.Cast<DataColumn>().Select(c=>"CONVERT(["+c.ColumnName+"], 'System.String') LIKE '%"+q.Replace("'","''")+"%'");try{dv.RowFilter=string.Join(" OR ",parts);}catch{}}grid.DataSource=dv;count.Text=(App.Persian?"تعداد رکورد: ":"Records: ")+dv.Count;}
void Delete(){if(grid.CurrentRow==null)return;if(MessageBox.Show(App.Persian?"این رکورد حذف شود؟":"Delete this record?",Text,MessageBoxButtons.YesNo,MessageBoxIcon.Warning)!=DialogResult.Yes)return;((DataRowView)grid.CurrentRow.DataBoundItem).Row.Delete();DataStore.Save();Bind();}
void Edit(DataRow row){var f=new Form{Text=(row==null?App.T("add"):App.T("edit"))+" — "+Text,Width=580,Height=Math.Min(760,190+DataStore.Db.Tables[table].Columns.Count*58),StartPosition=FormStartPosition.CenterParent,BackColor=Ui.Bg,AutoScroll=true,MinimizeBox=false,MaximizeBox=false};var head=new Panel{Dock=DockStyle.Top,Height=72,BackColor=Ui.Navy,Padding=new Padding(22)};head.Controls.Add(new Label{Text=f.Text,Dock=DockStyle.Fill,ForeColor=Color.White,Font=Ui.Font(15,FontStyle.Bold),TextAlign=App.Persian?ContentAlignment.MiddleRight:ContentAlignment.MiddleLeft});f.Controls.Add(head);var card=Ui.SurfacePanel();card.Dock=DockStyle.Fill;var panel=new TableLayoutPanel{Dock=DockStyle.Top,AutoSize=true,ColumnCount=2,Padding=new Padding(14)};panel.ColumnStyles.Add(new ColumnStyle(SizeType.Percent,32));panel.ColumnStyles.Add(new ColumnStyle(SizeType.Percent,68));var boxes=new TextBox[DataStore.Db.Tables[table].Columns.Count];for(int i=0;i<boxes.Length;i++){var c=DataStore.Db.Tables[table].Columns[i];panel.RowStyles.Add(new RowStyle(SizeType.Absolute,52));panel.Controls.Add(new Label{Text=c.ColumnName,Dock=DockStyle.Fill,Font=Ui.Font(9.5f,FontStyle.Bold),ForeColor=Ui.Text,TextAlign=App.Persian?ContentAlignment.MiddleRight:ContentAlignment.MiddleLeft},0,i);boxes[i]=new TextBox{Dock=DockStyle.Fill,Text=row==null?(i==0?DataStore.Next(table):""):row[i].ToString(),Margin=new Padding(6,9,6,7)};if(i==0)boxes[i].ReadOnly=true;panel.Controls.Add(boxes[i],1,i);}var save=Ui.Btn(App.T("save"));save.Width=150;save.Click+=(s,e)=>{if(row==null){var r=DataStore.Db.Tables[table].NewRow();for(int i=0;i<boxes.Length;i++)r[i]=boxes[i].Text;DataStore.Db.Tables[table].Rows.Add(r);}else for(int i=0;i<boxes.Length;i++)row[i]=boxes[i].Text;DataStore.Save();f.DialogResult=DialogResult.OK;f.Close();};panel.Controls.Add(save,1,boxes.Length);card.Controls.Add(panel);f.Controls.Add(card);card.BringToFront();App.ApplyDirection(f);f.ShowDialog(this);Bind();}}
}
