using System;using System.Data;using System.Drawing;using System.Windows.Forms;
namespace AshkanHotelManager{
 public partial class DirectoryForm:Form{
  readonly string table; DataGridView grid; TextBox search; Label count;
  public DirectoryForm(string tableName,string title){InitializeComponent();table=tableName;Text=title;Width=1180;Height=720;StartPosition=FormStartPosition.CenterParent;BackColor=Ui.Bg;MinimumSize=new Size(900,600);Build(title);}
  void Build(string title){var header=new Panel{Dock=DockStyle.Top,Height=104,BackColor=Ui.Surface,Padding=new Padding(28,18,28,12)};var h=Ui.H(title,21);h.Dock=DockStyle.Top;h.Height=38;var sub=new Label{Text=table=="Rooms"?App.T("roomBoard"):App.T("guestFolio"),Dock=DockStyle.Bottom,Height=26,ForeColor=Ui.Muted,Font=Ui.Font(9.5f),TextAlign=App.Persian?ContentAlignment.MiddleRight:ContentAlignment.MiddleLeft};header.Controls.Add(sub);header.Controls.Add(h);Controls.Add(header);
   var toolbar=Ui.SurfacePanel();toolbar.Dock=DockStyle.Top;toolbar.Height=82;toolbar.Padding=new Padding(18);search=new TextBox{Width=300,Height=34,Font=Ui.Font(10),Text=""};search.Location=new Point(18,24);search.TextChanged+=(s,e)=>RefreshView();var add=Ui.Btn(App.T("add"));add.Width=125;add.Location=new Point(335,18);add.Click+=(s,e)=>OpenCrud();var refresh=Ui.Ghost(App.T("refresh"));refresh.Width=125;refresh.Location=new Point(470,18);refresh.Click+=(s,e)=>RefreshView();count=new Label{AutoSize=false,Width=220,Height=40,Location=new Point(620,20),Font=Ui.Font(9.5f,FontStyle.Bold),ForeColor=Ui.Muted,TextAlign=ContentAlignment.MiddleCenter};toolbar.Controls.AddRange(new Control[]{search,add,refresh,count});Controls.Add(toolbar);
   var host=new Panel{Dock=DockStyle.Fill,Padding=new Padding(22),BackColor=Ui.Bg};grid=new DataGridView{Dock=DockStyle.Fill};Ui.Grid(grid);grid.CellDoubleClick+=(s,e)=>{if(e.RowIndex>=0)OpenCrud();};host.Controls.Add(grid);Controls.Add(host);host.BringToFront();toolbar.BringToFront();header.BringToFront();RefreshView();App.ApplyDirection(this);}
  void RefreshView(){var src=DataStore.Db.Tables[table];var v=new DataView(src);var q=(search==null?"":search.Text).Trim().Replace("'","''");if(q.Length>0){if(table=="Rooms")v.RowFilter="Convert(Number, 'System.String') LIKE '%"+q+"%' OR Type LIKE '%"+q+"%' OR Status LIKE '%"+q+"%'";else v.RowFilter="FullName LIKE '%"+q+"%' OR Phone LIKE '%"+q+"%' OR NationalId LIKE '%"+q+"%'";}grid.DataSource=v;count.Text=v.Count+"  "+(table=="Rooms"?App.T("rooms"):App.T("guests"));}
  void OpenCrud(){using(var f=new CrudForm(table,table=="Rooms"?App.T("rooms"):App.T("guests")))f.ShowDialog(this);RefreshView();}
 }
}