using System;using System.Data;using System.Drawing;using System.Linq;using System.Windows.Forms;
namespace AshkanHotelManager
{
 public partial class MainForm:Form
 {
  Panel content,side; Image hotelBackground;
  public MainForm(){InitializeComponent();WindowState=FormWindowState.Maximized;MinimumSize=new Size(1180,720);BackColor=Ui.Navy;hotelBackground=PremiumAssets.TryLoad("hotel-hero.jpg");BuildShell();}
  void BuildShell(){SuspendLayout();Controls.Clear();Text=App.T("title");RightToLeft=App.Persian?RightToLeft.Yes:RightToLeft.No;RightToLeftLayout=false;content=new PremiumBackgroundPanel{Dock=DockStyle.Fill,BackgroundArtwork=hotelBackground,OverlayAlpha=105,Padding=new Padding(30,84,30,30)};side=new Panel{Dock=App.Persian?DockStyle.Right:DockStyle.Left,Width=285,BackColor=Ui.Navy,Padding=new Padding(14)};Controls.Add(content);Controls.Add(side);side.BringToFront();BuildSide();BuildUtilityBar();App.ApplyDirection(this);side.Dock=App.Persian?DockStyle.Right:DockStyle.Left;Dashboard();ResumeLayout(true);}
  void BuildUtilityBar(){var bar=new Panel{Dock=DockStyle.Top,Height=64,BackColor=Color.FromArgb(238,16,27,46),Padding=new Padding(22,10,22,10)};var search=new TextBox{Width=330,Height=34,Font=Ui.Font(10),Text=App.Persian?"جستجوی مهمان، اتاق یا رزرو...":"Search guest, room or reservation..."};search.ForeColor=Ui.Muted;search.GotFocus+=(s,e)=>{if(search.ForeColor==Ui.Muted){search.Text="";search.ForeColor=Ui.Text;}};search.KeyDown+=(s,e)=>{if(e.KeyCode==Keys.Enter){using(var f=new GlobalSearchForm(search.ForeColor==Ui.Muted?"":search.Text))f.ShowDialog(this);}};var notify=Ui.Ghost(App.T("notifications"));notify.Width=145;notify.Click+=(s,e)=>{using(var f=new NotificationCenterForm())f.ShowDialog(this);};var user=new Label{Text=App.User+"  •  "+App.Role,AutoSize=false,Width=160,Height=40,Font=Ui.Font(9.5f,FontStyle.Bold),ForeColor=Ui.Text,TextAlign=ContentAlignment.MiddleCenter};if(App.Persian){notify.Dock=DockStyle.Left;user.Dock=DockStyle.Left;search.Dock=DockStyle.Right;}else{notify.Dock=DockStyle.Right;user.Dock=DockStyle.Right;search.Dock=DockStyle.Left;}bar.Controls.Add(search);bar.Controls.Add(notify);bar.Controls.Add(user);Controls.Add(bar);bar.BringToFront();side.BringToFront();}
  void BuildSide(){side.Controls.Clear();var brand=new Panel{Dock=DockStyle.Top,Height=132,BackColor=Ui.Navy};brand.Controls.Add(new Label{Text="A",Width=46,Height=46,Location=new Point(18,23),BackColor=Ui.Blue,ForeColor=Color.White,Font=Ui.Font(20,FontStyle.Bold),TextAlign=ContentAlignment.MiddleCenter});brand.Controls.Add(new Label{Text="AURORASTAY\nOPERATIONS",AutoSize=false,Width=145,Height=55,Location=new Point(78,20),ForeColor=Color.White,Font=Ui.Font(11,FontStyle.Bold),TextAlign=ContentAlignment.MiddleLeft});var languageButton=new Button{Text=App.Persian?"🌐  English":"🌐  فارسی",Dock=DockStyle.Bottom,Height=42,FlatStyle=FlatStyle.Flat,BackColor=Color.FromArgb(30,45,70),ForeColor=Color.White,Font=Ui.Font(9.5f,FontStyle.Bold),Cursor=Cursors.Hand};languageButton.FlatAppearance.BorderColor=Color.FromArgb(65,82,110);languageButton.Click+=(s,e)=>{App.SetLanguage(!App.Persian);BuildShell();};brand.Controls.Add(languageButton);side.Controls.Add(brand);string[] keys={"dashboard","operationsCenter","guestIntelligence","roomBoard","calendar","rooms","guests","guestFolio","reservations","billing","housekeeping","adminCenter","reports","settings"};foreach(var key in keys.Reverse()){var b=new Button{Text=App.T(key),Dock=DockStyle.Top,Height=54,FlatStyle=FlatStyle.Flat,BackColor=Ui.Navy,ForeColor=Color.White,Font=Ui.Font(10,FontStyle.Bold),TextAlign=App.Persian?ContentAlignment.MiddleRight:ContentAlignment.MiddleLeft,Tag=key,Padding=new Padding(15,0,15,0),Cursor=Cursors.Hand};b.FlatAppearance.BorderSize=0;b.FlatAppearance.MouseOverBackColor=Ui.NavyHover;b.Click+=Nav;side.Controls.Add(b);}var footer=new Label{Text="Portfolio Final RC  •  C# / .NET Framework 4.8",Dock=DockStyle.Bottom,Height=45,ForeColor=Color.FromArgb(148,163,184),Font=Ui.Font(8),TextAlign=ContentAlignment.MiddleCenter};side.Controls.Add(footer);}
  void Nav(object sender,EventArgs e){string k=(string)((Button)sender).Tag;if(k=="dashboard")Dashboard();else if(k=="operationsCenter"){using(var f=new OperationsCommandCenterForm())f.ShowDialog(this);Dashboard();}else if(k=="guestIntelligence"){using(var f=new GuestIntelligenceForm())f.ShowDialog(this);Dashboard();}else if(k=="roomBoard"){using(var f=new RoomBoardForm())f.ShowDialog(this);Dashboard();}else if(k=="reservations")Reservations();else if(k=="rooms"){using(var f=new DirectoryForm("Rooms",App.T("roomDirectory")))f.ShowDialog(this);Dashboard();}else if(k=="guests"){using(var f=new DirectoryForm("Guests",App.T("guestDirectory")))f.ShowDialog(this);Dashboard();}else if(k=="calendar"){using(var f=new ReservationCalendarForm())f.ShowDialog(this);}else if(k=="guestFolio"){using(var f=new GuestFolioForm())f.ShowDialog(this);}else if(k=="housekeeping"){using(var f=new HousekeepingBoardForm())f.ShowDialog(this);Dashboard();}else if(k=="adminCenter"){using(var f=new AdminCenterForm())f.ShowDialog(this);Dashboard();}else if(k=="reports")Reports();else if(k=="settings")Settings();else using(var f=new CrudForm(char.ToUpper(k[0])+k.Substring(1),App.T(k)))f.ShowDialog(this);}
  Label Header(string title,string sub){var wrap=new Panel{Dock=DockStyle.Top,Height=82};var h=new Label{Text=title,Dock=DockStyle.Top,Height=42,Font=Ui.Font(24,FontStyle.Bold),ForeColor=Color.White,TextAlign=App.Persian?ContentAlignment.MiddleRight:ContentAlignment.MiddleLeft};var s=new Label{Text=sub,Dock=DockStyle.Top,Height=30,Font=Ui.Font(9.5f),ForeColor=Color.FromArgb(220,235,245,255),TextAlign=App.Persian?ContentAlignment.MiddleRight:ContentAlignment.MiddleLeft};wrap.Controls.Add(s);wrap.Controls.Add(h);content.Controls.Add(wrap);return h;}
  void Dashboard(){content.SuspendLayout();content.Controls.Clear();Header(App.T("dashboard"),String.Format(App.T("welcomeUser"),App.User)+"  •  "+DateTime.Now.ToString("yyyy/MM/dd"));var snapshot=HotelMetrics.Today();int total=snapshot.TotalRooms,free=snapshot.AvailableRooms,occ=snapshot.OccupiedRooms,rate=snapshot.OccupancyPercent;decimal rev=snapshot.Revenue;
   var cards=new FlowLayoutPanel{Dock=DockStyle.Top,Height=150,Padding=new Padding(0,4,0,8),FlowDirection=App.Persian?FlowDirection.RightToLeft:FlowDirection.LeftToRight,WrapContents=false};cards.Controls.Add(Card(App.T("totalRooms"),total.ToString(),Ui.Blue,"ROOMS"));cards.Controls.Add(Card(App.T("available"),free.ToString(),Ui.Green,"READY"));cards.Controls.Add(Card(App.T("occupancy"),rate+"%",Ui.Warning,"LIVE"));cards.Controls.Add(Card(App.T("reservations"),snapshot.ActiveReservations.ToString(),Ui.Cyan,"BOOK"));cards.Controls.Add(Card(App.T("revenue"),rev.ToString("N0"),Ui.Navy,"$"));content.Controls.Add(cards);
   var quick=Ui.SurfacePanel();quick.Dock=DockStyle.Top;quick.Height=105;var qt=new Label{Text=App.T("quickActions"),Dock=DockStyle.Top,Height=28,Font=Ui.Font(11,FontStyle.Bold),ForeColor=Ui.Text,TextAlign=App.Persian?ContentAlignment.MiddleRight:ContentAlignment.MiddleLeft};var actions=new FlowLayoutPanel{Dock=DockStyle.Fill,FlowDirection=App.Persian?FlowDirection.RightToLeft:FlowDirection.LeftToRight};var nr=Ui.Btn(App.T("newReservation"));nr.Width=165;nr.Click+=(s,e)=>NewReservation();var rb=Ui.Ghost(App.T("roomBoard"));rb.Width=190;rb.Click+=(s,e)=>{using(var f=new RoomBoardForm())f.ShowDialog(this);Dashboard();};var gs=Ui.Ghost(App.T("guests"));gs.Width=145;gs.Click+=(s,e)=>{using(var f=new DirectoryForm("Guests",App.T("guestDirectory")))f.ShowDialog(this);Dashboard();};var hk=Ui.Ghost(App.T("housekeepingBoard"));hk.Width=170;hk.Click+=(s,e)=>{using(var f=new HousekeepingBoardForm())f.ShowDialog(this);Dashboard();};actions.Controls.AddRange(new Control[]{nr,rb,gs,hk});quick.Controls.Add(actions);quick.Controls.Add(qt);content.Controls.Add(quick);
   var lower=new TableLayoutPanel{Dock=DockStyle.Fill,ColumnCount=2,Padding=new Padding(0,14,0,0)};lower.ColumnStyles.Add(new ColumnStyle(SizeType.Percent,60));lower.ColumnStyles.Add(new ColumnStyle(SizeType.Percent,40));lower.Controls.Add(Recent(),0,0);lower.Controls.Add(RoomMix(total,free,occ),1,0);content.Controls.Add(lower);lower.BringToFront();quick.BringToFront();cards.BringToFront();content.ResumeLayout();App.ApplyDirection(content);}
  Control Card(string name,string value,Color accent,string badge){var p=new GlassPanel{Width=215,Height=124,GlassColor=Color.FromArgb(224,24,35,56),Margin=new Padding(7),Padding=new Padding(15)};var tag=new Label{Text=badge,AutoSize=true,BackColor=Color.FromArgb(35,49,75),ForeColor=accent,Font=Ui.Font(7.5f,FontStyle.Bold),Padding=new Padding(5),Location=new Point(14,12)};var val=new Label{Text=value,Dock=DockStyle.Top,Height=60,Font=Ui.Font(24,FontStyle.Bold),ForeColor=accent,TextAlign=App.Persian?ContentAlignment.MiddleRight:ContentAlignment.MiddleLeft};var nm=new Label{Text=name,Dock=DockStyle.Bottom,Height=27,Font=Ui.Font(9.5f),ForeColor=Ui.Muted,TextAlign=App.Persian?ContentAlignment.MiddleRight:ContentAlignment.MiddleLeft};p.Controls.Add(nm);p.Controls.Add(val);p.Controls.Add(tag);tag.BringToFront();return p;}
  Control Recent(){var p=Ui.SurfacePanel();p.Dock=DockStyle.Fill;var t=new Label{Text=App.T("recentReservations"),Dock=DockStyle.Top,Height=35,Font=Ui.Font(12,FontStyle.Bold),ForeColor=Ui.Text,TextAlign=App.Persian?ContentAlignment.MiddleRight:ContentAlignment.MiddleLeft};var g=new DataGridView{Dock=DockStyle.Fill};Ui.Grid(g);var dt=DataStore.Db.Tables["Reservations"].Clone();foreach(DataRow r in DataStore.Db.Tables["Reservations"].Rows.Cast<DataRow>().Reverse().Take(6))dt.ImportRow(r);g.DataSource=dt;p.Controls.Add(g);p.Controls.Add(t);return p;}
  Control RoomMix(int total,int free,int occ){var p=Ui.SurfacePanel();p.Dock=DockStyle.Fill;var t=new Label{Text=App.T("roomMix"),Dock=DockStyle.Top,Height=42,Font=Ui.Font(12,FontStyle.Bold),ForeColor=Ui.Text,TextAlign=App.Persian?ContentAlignment.MiddleRight:ContentAlignment.MiddleLeft};p.Controls.Add(t);int clean=DataStore.Db.Tables["Rooms"].Select("Status = 'Cleaning'").Length,maint=DataStore.Db.Tables["Rooms"].Select("Status = 'Maintenance'").Length;var list=new FlowLayoutPanel{Dock=DockStyle.Fill,FlowDirection=FlowDirection.TopDown,WrapContents=false};list.Controls.Add(StatusRow(App.T("available"),free,total,Ui.Green));list.Controls.Add(StatusRow(App.T("occupied"),occ,total,Ui.Blue));list.Controls.Add(StatusRow(App.T("cleaning"),clean,total,Ui.Warning));list.Controls.Add(StatusRow(App.T("maintenance"),maint,total,Ui.Danger));p.Controls.Add(list);list.BringToFront();return p;}
  Control StatusRow(string text,int n,int total,Color c){var p=new Panel{Width=330,Height=58,Margin=new Padding(4)};var l=new Label{Text=text+"   "+n,Dock=DockStyle.Top,Height=28,Font=Ui.Font(9.5f,FontStyle.Bold),ForeColor=Ui.Text,TextAlign=App.Persian?ContentAlignment.MiddleRight:ContentAlignment.MiddleLeft};var bg=new Panel{Dock=DockStyle.Bottom,Height=8,BackColor=Ui.Border};var bar=new Panel{Dock=App.Persian?DockStyle.Right:DockStyle.Left,Width=total==0?0:(int)(300.0*n/total),BackColor=c};bg.Controls.Add(bar);p.Controls.Add(bg);p.Controls.Add(l);return p;}
  void NewReservation(){using(var f=new ReservationForm())if(f.ShowDialog(this)==DialogResult.OK)Dashboard();}
  void Reservations(){content.Controls.Clear();Header(App.T("reservations"),App.T("availability"));var bar=Ui.SurfacePanel();bar.Dock=DockStyle.Top;bar.Height=82;var n=Ui.Btn(App.T("newReservation"));n.Width=170;n.Click+=(s,e)=>{NewReservation();};var m=Ui.Ghost(App.T("openReservations"));m.Width=180;m.Click+=(s,e)=>{using(var f=new CrudForm("Reservations",App.T("reservations")))f.ShowDialog(this);Reservations();};bar.Controls.Add(n);bar.Controls.Add(m);m.Location=new Point(200,18);n.Location=new Point(18,18);content.Controls.Add(bar);var g=new DataGridView{Dock=DockStyle.Fill};Ui.Grid(g);g.DataSource=new DataView(DataStore.Db.Tables["Reservations"]);g.CellFormatting+=(s,e)=>Ui.FormatStatusCell(g,e);content.Controls.Add(g);g.BringToFront();bar.BringToFront();App.ApplyDirection(content);}
  void Reports(){content.Controls.Clear();Header(App.T("reports"),App.T("hotelOverview"));var g=new DataGridView{Dock=DockStyle.Fill};Ui.Grid(g);var t=new DataTable();t.Columns.Add(App.Persian?"شاخص":"Metric");t.Columns.Add(App.Persian?"مقدار":"Value");t.Rows.Add(App.T("totalRooms"),DataStore.Db.Tables["Rooms"].Rows.Count);t.Rows.Add(App.T("guests"),DataStore.Db.Tables["Guests"].Rows.Count);t.Rows.Add(App.T("reservations"),DataStore.Db.Tables["Reservations"].Rows.Count);t.Rows.Add(App.T("billing"),DataStore.Db.Tables["Billing"].Rows.Count);g.DataSource=t;content.Controls.Add(g);g.BringToFront();App.ApplyDirection(content);}
  void Settings(){content.Controls.Clear();Header(App.T("settings"),App.T("language"));var p=Ui.SurfacePanel();p.Dock=DockStyle.Top;p.Height=130;var b=Ui.Btn(App.Persian?"English — LTR":"فارسی — RTL");b.Width=200;b.Location=new Point(22,35);b.Click+=(s,e)=>{App.SetLanguage(!App.Persian);BuildShell();};p.Controls.Add(b);content.Controls.Add(p);p.BringToFront();App.ApplyDirection(content);}
 }
}
